### ISSUE TITLE
Improve Display Method 

### ISSUE THREAD

**Issue by t170815518** [AY2021S1-CS2113-T13-4/tp#54]
1. Display the lesson with more information, such as the weekday. `[L]tutorial CS2113 13:00 14:00` is not sufficient.
2. Display the lesson when to display all the tasks of a module on a given date as well. 
For instance, the tutorial is on `2020/10/15` but not displayed.
```
===================
display CS2113 

Course: CS2113
Title: null
AU: 0
Teaching Staffs: []
The list of task in CS2113:
[L]tutorial CS2113 13:00 14:00
[D]CS2113 Tp version 1 (by: 2020-10-15)

===================
===================
Please type the command!
===================
display CS2113 /date 2020/10/15
The list of task in CS2113 on 2020-10-15 :
[D]CS2113 Tp version 1 (by: 2020-10-15)

===================
```
3. **Deadline and Lesson are mixed?** 
```
===================
deadline CS2113 Tp version 1 /by 2020-10-15
Got it, added deadline to Schedule Manager and Module Manager
===================
===================
display /date 2020/10/15
Here is your schedule on 2020-10-15!! :)
08:00
09:00
10:00
11:00
12:00
13:00 tutorial, CS2113 Tp version 1, CS2113
14:00
15:00
16:00
17:00
18:00
19:00
20:00
21:00
22:00
23:00

Deadlines on 2020-10-15:
You don't have any tasks!

===================
```

**Comment by acyang97** [comment]
At the bottom of ModuleManager, should put all sorts of task under it - Lesson, Deadlines and Events. 
At the bottom of ScheduleManager, should just put in the Deadlines -  should put down deadlines today and future as well. Will think of how to implement this and  update later
